name = 'Odie - A Hugo Theme for Open 3D Engine'
license = 'MIT'
licenselink = 'https://github.com/o3de/hugo-odie/LICENSE'
description = "The Hugo theme designed for Open 3D Engine's documentation site. Named for its mascot, Odie."

# The home page of the theme, where the source can be found
homepage = 'https://github.com/o3de/hugo-odie'

# If you have a running demo of the theme
demosite = 'https://docs.o3de.org'

# Taxonomy terms
tags = []
features = []

# If the theme has a single author
[author]
  name = 'O3DE Docs Team'
  homepage = 'https://github.com/o3de/sig-docs-community'
